Don't verify HTTPS in init.py

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -59,10 +59,13 @@ jobs:
             tries=10
             until services=$(sqlite3 data/statping/statping.db "select count(*) from services")
             do
-               sleep 1
-               [[ tries -lt 1 ]] && echo "Could not read statping.db" && exit 1
-               ((tries--))
+              echo "Waiting for DB..."
+              sleep 1
+              [[ tries -lt 1 ]] && echo "Could not read statping.db" && exit 1
+              ((tries--))
             done
+
+            echo "Available services: $services"
 
             test $services -gt 0 || \
               API_URL=https://${{ github.event.inputs.environment }}/api \
